/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#dbd9dc",
        "secondary-fixed": "#ffddb8",
        "on-surface": "#1b1c1d",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303032",
        "tertiary-fixed-dim": "#e6c093",
        "on-tertiary-fixed-variant": "#5c421f",
        "on-background": "#1b1c1d",
        "secondary": "#855300",
        "tertiary": "#100700",
        "surface-variant": "#e4e2e4",
        "primary-fixed": "#d2e4ff",
        "secondary-container": "#fea619",
        "primary": "#000917",
        "on-primary-fixed-variant": "#364860",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-fixed": "#081c32",
        "outline-variant": "#c4c6cd",
        "on-tertiary-container": "#a28259",
        "surface-tint": "#4d6079",
        "on-primary": "#ffffff",
        "tertiary-container": "#301c00",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2a1800",
        "error": "#ba1a1a",
        "background": "#fbf9fb",
        "primary-container": "#0d2137",
        "on-surface-variant": "#44474d",
        "on-primary-container": "#7689a4",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f2f0f2",
        "surface-bright": "#fbf9fb",
        "surface": "#fbf9fb",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb5",
        "on-error-container": "#93000a",
        "inverse-primary": "#b5c8e5",
        "primary-fixed-dim": "#b5c8e5",
        "on-secondary-fixed": "#2a1700",
        "surface-container-high": "#e9e7ea",
        "on-error": "#ffffff",
        "surface-container": "#efedef",
        "surface-container-low": "#f5f3f5",
        "outline": "#74777d",
        "on-secondary-fixed-variant": "#653e00",
        "on-secondary-container": "#684000",
        "surface-container-highest": "#e4e2e4"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-padding": "80px",
        "gutter": "24px",
        "container-max": "1200px",
        "stack-md": "24px",
        "base": "8px",
        "stack-lg": "48px",
        "stack-sm": "12px",
        "card-padding": "32px"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      },
      "boxShadow": {
        "ambient": "0px 4px 20px rgba(13, 33, 55, 0.05)",
        "ambient-md": "0px 8px 30px rgba(13, 33, 55, 0.08)",
        "ambient-lg": "0px 12px 40px rgba(13, 33, 55, 0.12)",
      }
    },
  },
  plugins: [],
}
